[build]
  base = ""
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
