services:
  - type: web
    name: client
    env: node
    repo: https://github.com/relaya17/my-monorepo
    branch: main
    rootDir: client
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm exec serve -s dist -l 0.0.0.0:$PORT
    buildFilter:
      paths:
        - client/**

  - type: web
    name: api
    env: node
    repo: https://github.com/relaya17/my-monorepo
    branch: main
    rootDir: server
    buildCommand: pnpm install && pnpm run build
    startCommand: node dist/index.js
    buildFilter:
      paths:
        - server/**
