// routes.ts
const ROUTES = {
  HOME: "/",
  LANDING: "/landing",
  LANDING_TECHNICIAN: "/landing/technician",
  LANDING_RESIDENT: "/landing/resident",
  REGISTER: "/register",
  LOGIN: "/login",
  RESIDENT_FORM: "/resident-form",
  EMPLOYEE_MANAGEMENT: "/employee-management",
  NEW_RESIDENT_APPROVAL: "/new-resident-approval",
  REPAIR_TRACKING: "/repair-tracking",
  GARDENING: "/gardening",
  FOR_RENT: "/for-rent",
  FOR_SALE: "/for-sale",

  THANK_YOU: "/thank-you",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  ACCESSIBILITY: "/accessibility",
  SECURITY_POLICY: "/security-policy",
  CREATE_ADMIN_PASSWORD: "/create-admin-password",
  USER_DETAILS: "/user-details/:id",
  USERS_LIST: "/users-list",
  USER_MANAGEMENT: "/user-management",
  CHANGE_ADMIN_PASSWORD: "/change-admin-password",
  SIGN_UP: "/sign-up",
  CHECK_OUT: "/check-out",
  ADMIN_DASHBOARD: "/admin-dashboard",
  ADMIN_LOGIN: "/admin-login",
  SELECT_BUILDING: "/select-building",
  CHANGE_PASSWORD: "/change-password",
  USER_LOGIN: "/user-login",
  FORGOT_PASSWORD: "/forgot-password",
  USER_DASHBOARD: "/user-dashboard",
  RECEIPT: "/receipt",
  VOTING: "/voting",
  RESIDENT_HOME: "/resident-home",
  COMMUNITY_WALL: "/community-wall",
  AI_DASHBOARD: "/ai-dashboard",
  PAYMENT_MANAGEMENT: "/payment-management",
  APARTMENT_MANAGEMENT: "/apartments",
  REPORTS_DASHBOARD: "/reports-dashboard",
  MAINTENANCE_MANAGEMENT: "/maintenance",
  SYSTEM_SETTINGS: "/settings",
  CONTRACTS_AND_LETTERS: "/contracts-letters",
  SAFE_ZONE: "/safe-zone",
  B2B_REGISTER: "/enterprise-register",
  /** Friendly URL for SEO: vantera.co.il/contractors-join */
  CONTRACTORS_JOIN: "/contractors-join",
  /** Friendly URL for SEO: vantera.co.il/companies-management */
  COMPANIES_MANAGEMENT: "/companies-management",
  SALES_TOOLKIT: "/sales-toolkit",
};

export default ROUTES;
